"""Portal business logic: VPN profile issuance and first-time setup.

Profile issuance follows the "download a fresh profile" model used by
enterprise VPN portals: every download generates a new ML-DSA key pair and
certificate, records the certificate serial as the user's *only* valid one,
and returns the private key exactly once.  The portal never stores private
keys, and a lost device is handled by downloading a new profile (which
invalidates the old one) or by disabling the account.
"""

from __future__ import annotations

import base64
import io
import ipaddress
import os
import time
import zipfile

from .. import pki
from ..config import PortalConfig
from ..crypto import ossl
from ..crypto.suites import DEFAULT_SUITES, sig_alg_by_name
from .store import Store, secure_file


class CA:
    def __init__(self, cfg: PortalConfig):
        self.cert = pki.Certificate.load(cfg.ca_certificate)
        self.key = pki.read_private_key(cfg.ca_private_key, cfg.ca_passphrase)
        if self.cert.key_alg.public_bytes(self.key) != self.cert.public_key:
            raise pki.CertError("CA key does not match CA certificate")
        with open(cfg.ca_certificate, encoding="ascii") as f:
            self.pem = f.read()


CLIENT_TEMPLATE = """\
# pqvpn client profile for {username} -- issued {issued} by {issuer}
# Generated by the portal; downloading a new profile invalidates this one.
[client]
server = "{endpoint}"
server_name = "{server_name}"
certificate = "{username}.crt"
private_key = "{username}.key"
ca = ["ca.crt"]
portal_url = "{portal_url}"

[tunnel]
interface = "pqvpn0"
mtu = 1420
full_tunnel = false
routes = []
use_server_dns = true
persistent_keepalive = 25

[crypto]
suites = [{suites}]
peer_signature_algorithms = ["ML-DSA-65", "ML-DSA-87"]
ca_signature_algorithms = ["{ca_alg}"]
rekey_interval = 120
{psk_line}"""

README = """\
{issuer} -- VPN profile for {username}
=====================================

Windows (with the taskbar app):
    python -m pqvpn tray -c client.toml
Command line (Windows: Administrator terminal / Linux: sudo):
    python -m pqvpn client -c client.toml

Your VPN address: {address}
Certificate serial: {serial} (valid until {expires})

Keep {username}.key secret. Downloading a new profile from the portal
invalidates this one.
"""


def issue_profile(cfg: PortalConfig, store: Store, ca: CA, user: dict) -> tuple[bytes, pki.Certificate]:
    if not user["vpn_ip"]:
        ip = store.allocate_ip(cfg.subnet, cfg.reserved_addresses)
        store.update_user(user["id"], vpn_ip=ip)
        user = {**user, "vpn_ip": ip}
    alg = sig_alg_by_name(cfg.client_algorithm)
    key = alg.generate()
    cert = pki.issue(role=pki.ROLE_CLIENT, subject=user["username"], key_alg=alg,
                     public_key=alg.public_bytes(key), addresses=[f"{user['vpn_ip']}/32"],
                     days=cfg.certificate_days, issuer_key=ca.key, issuer_alg=ca.cert.key_alg,
                     issuer_public=ca.cert.public_key)
    store.update_user(user["id"], active_serial=cert.serial_hex, profile_issued_at=int(time.time()))

    name = user["username"]
    psk_line = ""
    files = {}
    if cfg.psk_file:
        with open(cfg.psk_file, encoding="ascii") as f:
            files["psk.key"] = f.read()
        psk_line = 'psk_file = "psk.key"\n'
    issued = time.strftime("%Y-%m-%d %H:%M UTC", time.gmtime())
    files["client.toml"] = CLIENT_TEMPLATE.format(
        username=name, issued=issued, issuer=cfg.issuer, endpoint=cfg.endpoint, server_name=cfg.server_name,
        portal_url=cfg.vpn_portal_url or cfg.public_url, suites=", ".join(f'"{s}"' for s in cfg.suites),
        ca_alg=ca.cert.key_alg.name, psk_line=psk_line)
    files[f"{name}.crt"] = cert.to_pem()
    files[f"{name}.key"] = ossl.private_to_pem(key).decode("ascii")
    files["ca.crt"] = ca.pem
    files["README.txt"] = README.format(
        issuer=cfg.issuer, username=name, address=user["vpn_ip"], serial=cert.serial_hex,
        expires=time.strftime("%Y-%m-%d", time.gmtime(cert.not_after)))
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as z:
        for fname, content in files.items():
            z.writestr(f"pqvpn-{name}/{fname}", content)
    return buf.getvalue(), cert


# ------------------------------------------------------------------ first-time setup

SERVER_TOML = """\
# pqvpn server -- created by `pqvpn portal-init`
[server]
listen = "{listen}"
certificate = "server/server.crt"
private_key = "server/server.key"
ca = ["ca/ca.crt"]

[tunnel]
interface = "pqvpn0"
mtu = 1420
dns = []
push_routes = ["{subnet}"]
nat_interface = "{nat}"

[crypto]
suites = [{suites}]
peer_signature_algorithms = ["ML-DSA-65", "ML-DSA-87"]
ca_signature_algorithms = ["{ca_alg}"]
rekey_interval = 120
{psk_line}
[portal]
database = "portal.db"        # only accounts enabled in the portal may connect
url = "{vpn_portal_url}"      # pushed to clients ("Open portal" in the tray app)
"""

PORTAL_TOML = """\
# pqvpn web portal -- created by `pqvpn portal-init`
[portal]
listen = [{listen}]
public_url = "{public_url}"
database = "portal.db"
issuer = "{issuer}"
require_2fa_for_admins = true     # administrators must set up an authenticator app at first sign-in
session_idle_minutes = 30
session_max_hours = 12
# For access from untrusted networks, add a certificate (e.g. Let's Encrypt):
# tls_certificate = "tls/fullchain.pem"
# tls_private_key = "tls/privkey.pem"

[vpn]
server_name = "{server_name}"
endpoint = "{endpoint}"
subnet = "{subnet}"
reserved_addresses = ["{server_ip}"]
ca_certificate = "ca/ca.crt"
ca_private_key = "ca/ca.key"
client_algorithm = "ML-DSA-65"
certificate_days = 90
portal_url_in_vpn = "{vpn_portal_url}"
{psk_cfg}"""


def portal_init(data: str, *, server_name: str, endpoint: str, subnet: str, admin: str,
                listen: list[str], public_url: str, issuer: str, psk: bool, nat: str,
                ca_alg: str = "SLH-DSA-SHA2-192s", server_listen: str = "0.0.0.0:51820") -> str:
    """Create CA, server identity, configs and the first admin.  Returns the admin's temp password."""
    from . import auth

    if os.path.exists(os.path.join(data, "portal.db")):
        raise SystemExit(f"{data} already contains a portal (portal.db exists)")
    net = ipaddress.ip_network(subnet, strict=True)
    server_ip = next(net.hosts())
    for d in ("ca", "server"):
        os.makedirs(os.path.join(data, d), exist_ok=True)
    try:
        os.chmod(data, 0o700)
    except OSError:
        pass

    alg = sig_alg_by_name(ca_alg)
    ca_key = alg.generate()
    ca_cert = pki.self_sign_ca(f"{issuer} Root CA", ca_key, alg, 3650)
    pki.write_private_key(os.path.join(data, "ca", "ca.key"), ca_key)
    pki.write_file(os.path.join(data, "ca", "ca.crt"), ca_cert.to_pem())

    s_alg = sig_alg_by_name("ML-DSA-65")
    s_key = s_alg.generate()
    s_cert = pki.issue(role=pki.ROLE_SERVER, subject=server_name, key_alg=s_alg,
                       public_key=s_alg.public_bytes(s_key), addresses=[f"{server_ip}/{net.prefixlen}"],
                       days=825, issuer_key=ca_key, issuer_alg=alg, issuer_public=ca_cert.public_key)
    pki.write_private_key(os.path.join(data, "server", "server.key"), s_key)
    pki.write_file(os.path.join(data, "server", "server.crt"), s_cert.to_pem())

    psk_line = psk_cfg = ""
    if psk:
        pki.write_file(os.path.join(data, "psk.key"), base64.b64encode(os.urandom(32)).decode() + "\n")
        secure_file(os.path.join(data, "psk.key"))
        psk_line = 'psk_file = "psk.key"\n'
        psk_cfg = 'psk_file = "psk.key"\n'
    vpn_portal_url = f"http://{server_ip}:{listen[0].rsplit(':', 1)[1]}/"
    suites = ", ".join(f'"{s}"' for s in DEFAULT_SUITES)
    pki.write_file(os.path.join(data, "server.toml"), SERVER_TOML.format(
        listen=server_listen, subnet=net, nat=nat, suites=suites, ca_alg=alg.name, psk_line=psk_line,
        vpn_portal_url=vpn_portal_url))
    pki.write_file(os.path.join(data, "portal.toml"), PORTAL_TOML.format(
        listen=", ".join(f'"{x}"' for x in listen), public_url=public_url, issuer=issuer,
        server_name=server_name, endpoint=endpoint, subnet=net, server_ip=server_ip,
        vpn_portal_url=vpn_portal_url, psk_cfg=psk_cfg))

    store = Store(os.path.join(data, "portal.db"))
    secure_file(os.path.join(data, "portal.db"))
    password = auth.generate_password()
    store.create_user(admin, "admin", password, display_name="Administrator", must_change=True)
    store.audit("portal_initialised", actor="setup", detail=f"admin={admin} ca={alg.name}")
    return password
